package nuc.bsd.psy.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnswer<M extends BaseAnswer<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPaperCode(java.lang.String paperCode) {
		set("paperCode", paperCode);
	}

	public java.lang.String getPaperCode() {
		return get("paperCode");
	}

	public void setStuId(java.lang.String stuId) {
		set("stuId", stuId);
	}

	public java.lang.String getStuId() {
		return get("stuId");
	}

	public void setQueCode(java.lang.String queCode) {
		set("queCode", queCode);
	}

	public java.lang.String getQueCode() {
		return get("queCode");
	}

	public void setQueAns(java.lang.Integer queAns) {
		set("queAns", queAns);
	}

	public java.lang.Integer getQueAns() {
		return get("queAns");
	}

	public void setQueSeq(java.lang.Long queSeq) {
		set("queSeq", queSeq);
	}

	public java.lang.Long getQueSeq() {
		return get("queSeq");
	}

	public void setSubmitTime(java.util.Date submitTime) {
		set("submitTime", submitTime);
	}

	public java.util.Date getSubmitTime() {
		return get("submitTime");
	}

	public void setSchoolId(java.lang.String schoolId) {
		set("schoolId", schoolId);
	}

	public java.lang.String getSchoolId() {
		return get("schoolId");
	}

	public void setGradeId(java.lang.String gradeId) {
		set("gradeId", gradeId);
	}

	public java.lang.String getGradeId() {
		return get("gradeId");
	}

	public void setClassId(java.lang.String classId) {
		set("classId", classId);
	}

	public java.lang.String getClassId() {
		return get("classId");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

}
