package nuc.bsd.psy.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGrade<M extends BaseGrade<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGrade(java.lang.String grade) {
		set("grade", grade);
	}

	public java.lang.String getGrade() {
		return get("grade");
	}

	public void setSchoolID(java.lang.String schoolID) {
		set("schoolID", schoolID);
	}

	public java.lang.String getSchoolID() {
		return get("schoolID");
	}

	public void setGradeID(java.lang.String gradeID) {
		set("gradeID", gradeID);
	}

	public java.lang.String getGradeID() {
		return get("gradeID");
	}

	public void setSchoolCode(java.lang.String schoolCode) {
		set("schoolCode", schoolCode);
	}

	public java.lang.String getSchoolCode() {
		return get("schoolCode");
	}

}
