package nuc.bsd.psy.base.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClass<M extends BaseClass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setGradeID(java.lang.String gradeID) {
		set("gradeID", gradeID);
	}

	public java.lang.String getGradeID() {
		return get("gradeID");
	}

	public void setClass(java.lang.String _class) {
		set("class", _class);
	}

	

	public void setClassID(java.lang.String classID) {
		set("classID", classID);
	}

	public java.lang.String getClassID() {
		return get("classID");
	}

}
